name: 'Beatmods 3 QMod automatic PR'
description: 'TODO'
author: 'Fernthedev'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Github token'
    required: true
    default: ''
  qmod_url:
    description: 'QMOD Url'
    required: true
    default: ''
  qmod_repo_owner:
    description: 'Repo owner for beatmods 3'
    required: true
    default: 'QuestPackageManager'
  qmod_repo_name:
    description: 'Repo  3'
    required: true
    default: 'beatmods3'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
